name = "bot"
main = "src/index.ts"
compatibility_date = "2022-05-03"
node_compat = true

[dev]
ip = "localhost"

#
#[site]
#bucket = "dist"

[[kv_namespaces]]
binding = "DATABASE"
id = ""

[vars]
IS_PROD = true
WAI_WORKER_API_TOKEN = ""
USER_ID_START = "623415"
USER_ID_SUPER_ADMIN = ""

OPENAI_API_KEY=""
FRONTEND_URL = "https://xxxx.dev"
BOT_WORKER_API='http://localhost:1236/api'
